<?php

/**
 * Plugin_4bPaymentDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Plugin_4bPaymentDataTable extends PaymentDataTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object Plugin_4bPaymentDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Plugin_4bPaymentData');
    }
}