# You can overwrite these values in your global app.yml
all:
  jmsPaymentPlugin:
    ###########################
    # PayPal related settings #
    ###########################
    paypal:
      # PayPal API credentials
      username: ~
      signature: ~
      password: ~
      
      # Whether people need a verified PayPal account for payments
      verified_account_required: false
      
    
    #######################################################
    # Micropayment related settings (www.micropayment.de) #
    #######################################################
    micropayment:
      access_key: ~
      
      # You can overwrite these values for each payment
      project: ~
      project_campaign: ~

    #######################################################
    # 4b system related settings (www.4b.com)             #
    #######################################################
    _4b:
      #store key provided for 4b system.
      store: ~
      production_url: "tpv.4b.es/tpvv/teargral.exe"
      production_ip: 194.224.159.47
      simulation_url: "https://tpv2.4b.es/simulador/teargral.exe"
      simulation_ip: 194.224.159.57
